config/routes.rb
Rails.application.routes.draw do

  resources :works
  resources :services
  devise_for :users

  get 'home/contact', as: :contact
  get 'home/about', as: :about

  authenticated :user do
    root 'home#register'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'home#index', as: :landing_root
    end
  end


end

app/models/service.rb
class Service < ActiveRecord::Base
  include Paperclip::Glue
  belongs_to :user
  has_many :service
  validates_presence_of :name

  has_attached_file :avatar, styles: {thumb: "20x20", medium: "80x80"}, default_url: "default.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :service
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :service
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'El servicio se creo correctamente.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'El servicio se ha actualizado.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'El servicio se ha eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :avatar)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Se ha agregado al curriculum.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Obra actualizada.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Eliminado del curriculum.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :company, :progress, :date_ini, :date_end, :service_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/home/_contactform.html.haml
%p  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
.col.s12.center
  %p
  = link_to 'Enviar', :class => "waves-effect waves-teal btn indigo"

app/views/home/_features.html.haml
.row
  .col.s12.center
    %h4 Conoce algunas de nuestras obras
    %p  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    .col.s12.center
      = link_to 'Ver más obras', works_path, :class => "waves-effect waves-teal btn indigo"

app/views/home/_slider.html.haml
.slider
  %ul.slides
    %li
      = image_tag "http://cajce.com.mx/img/foto4.jpg"
      .caption.center-align
        %h3 Somos los mejores en cada Servicio.
        %h5.light.grey-text.text-lighten-4 Désde 2006.

    %li
      = image_tag "http://cajce.com.mx/img/foto2.jpg"
      .caption.left-align
        %h3 Somos una empresa Mexicana.
        %h5.light.grey-text.text-lighten-4 Dedicada y comprometida con sus valores.

    %li
      = image_tag "http://cajce.com.mx/img/foto3.jpg"
      .caption.center-align
        %h3 Nos mantenemos a la vanguardia.
        %h5.light.grey-text.text-lighten-4 Responsables con el medio ambiente y la sociedad.

    %li
      = image_tag "http://cajce.com.mx/img/foto1.jpg"
      .caption.left-align
        %h3 La construcción es nuestra mayor fuerza.
        %h5.light.grey-text.text-lighten-4 Calidad en todo lo que hacemos.

app/views/home/about.html.haml
.row
  .col.s12.center
    %h4 Acerca de Nosotros

app/views/home/contact.html.haml
.row
  .col.s12.center
    %h4 Contáctanos
    %h6 Nos comunicaremos lo antes posible.

app/views/home/index.html.haml
= render "home/slider"

app/views/home/register.html.haml
= render "home/features"

= render "home/contactform"

app/views/layouts/_footer.html.haml
%footer.page-footer.indigo.lighten-1
  .container
    .row
      .col.l6.s12
        = image_tag("logo2.png", :alt=> "logo", :class=> "brand-logo logo-container responsive-img", :id=> "logo-container")
      .col.l3.s12
        %h5.white-text Contáctanos
        %ul
          %li.white-text
            %span.fa.fa-phone
              (55) 49 97 14 76
          %li.white-text
            %span.fa.fa-phone
              (55) 49 97 04 37
          %li.white-text
            %span.fa.fa-envelope
              ventas@cajce.com.mx

      .right.col.l3.s12
        %h5.white-text Síguenos
        %ul
          %li
            %p.white-text
              %span.fa.fa-facebook.fa-3x

  .footer-copyright
    .container
      %p.center Copyright &copy; 2016, Constructora Cajce S.A de C.V.

app/views/layouts/_navbar.html.haml
.navbar-fixed
  %nav.indigo
    .nav-wrapper
      = link_to (image_tag"logo.png", :alt=> "logo", :class=> "brand-logo logo-container responsive-img", :id=> "logo"), "#"
      %ul.right.hide-on-med-and-down
        %li
          = link_to "Acerca de Nosotros", about_path
        %li
          = link_to "Servicios", services_path
        %li
          = link_to "Obras", works_path
        %li
          = link_to "Contáctanos", contact_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Constructora Cajce S.A de C.V.</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => "layouts/navbar" %>

<% if notice %>
  <p class="alert alert-success center-align"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger center-align"><%= alert %></p>
<% end %>

<%= yield %>

<%= render :partial => "layouts/footer" %>

</body>
</html>

app/views/services/_form.html.haml
= form_for @service do |f|
  - if @service.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service.errors.count, "error")} prohibited this service from being saved:"
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description, :class => "materialize-textarea"
  .field
    = f.label :avatar
    = f.file_field :avatar
  .actions
    = f.submit 'Save'

app/views/services/_header.html.haml
%header

app/views/services/edit.html.haml
%h1 Editing service

= render 'form'

= link_to 'Show', @service
\|
= link_to 'Back', services_path

app/views/services/index.html.haml
.row
  .col.s12.center
    %h4 Nuestros servicios
    - if user_signed_in?
      %p
        = link_to '+', new_service_path, :class=>"btn-floating btn-large waves-effect waves-light indigo"
    - else
      %p


    - @services.each do |service|
      .col.s6.m3.l2
        .card-content
          = link_to (image_tag service.avatar.url(:medium), :class => "circle waves-effect waves-light animated fadeIn"), service
        .blue-grey-text.text-lighten-2.small.animated.zoomIn
          = service.name
        %p

app/views/services/new.html.haml
%h1 New service

= render 'form'

= link_to 'Back', services_path

app/views/services/show.html.haml
= render "services/header"
.row
  .col.s12.center
    %h4
      = @service.name
    %p
      = image_tag @service.avatar.url, :class => "circle animated fadeIn"

    .blue-grey-text.text-lighten-2.animated.zoomIn
      = @service.description

  .col.s12.center
    %p
    .card-action
      - if user_signed_in?
        = link_to 'Editar', edit_service_path(@service), :class => "waves-effect waves-teal btn indigo"
        = link_to 'Regresar', services_path, :class => "waves-effect waves-teal btn indigo"
        = link_to 'Eliminar', service_path, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "waves-effect waves-teal btn red"
      - else
        = link_to 'Regresar', services_path, :class => "waves-effect waves-teal btn indigo"

app/views/works/_form.html.haml
= form_for @work do |f|
  - if @work.errors.any?
    #error_explanation
      %h2= "#{pluralize(@work.errors.count, "error")} prohibited this work from being saved:"
      %ul
        - @work.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :company
    = f.text_field :company
  .field
    = f.label :progress
    = f.text_field :progress
  .field
    = f.label :date_ini
    = f.date_select :date_ini
  .field
    = f.label :date_end
    = f.date_select :date_end
  .field
    = f.label :service
    = f.text_field :service
  .actions
    = f.submit 'Save'

app/views/works/_header.html.haml
%header

app/views/works/edit.html.haml
%h1 Editing work

= render 'form'

= link_to 'Show', @work
\|
= link_to 'Back', works_path

app/views/works/index.html.haml
.row
  .col.s12.center
    %h4 Nuestras obras
    - if user_signed_in?
      %p
        = link_to '+', new_work_path, :class=>"btn-floating btn-large waves-effect waves-light indigo"
    - else
      %p

%table.highlight.responsive-table.centered
  %thead
    %tr
      %th
      %th Obra
      %th Empresa
      %th Progreso
      %th Fecha de inicio
      %th Fecha de termino
      %th Servicios

  %tbody
    - @works.each do |work|
      %tr
        %td= link_to 'Ver', work
        %td= work.name
        %td= work.company
        %td= work.progress
        %td= work.date_ini
        %td= work.date_end
        %td= work.service

app/views/works/new.html.haml
%h1 New work

= render 'form'

= link_to 'Back', works_path

app/views/works/show.html.haml
= render "services/header"
.row
  .col.s12.center
    %h4
      = @work.name
    .card
      %p
        %b
          = @work.company
      %p
        %b Progreso:
        = @work.progress
      %p
        %b Fecha de inicio:
        = @work.date_ini
      %p
        %b Fecha de termino:
        = @work.date_end
      %p
        %b Servicios:
        = @work.service

  .col.s12.center
    %p
    .card-action
      - if user_signed_in?
        = link_to 'Editar', edit_work_path(@work), :class => "waves-effect waves-teal btn indigo"
        = link_to 'Regresar', works_path, :class => "waves-effect waves-teal btn indigo"
        = link_to 'Eliminar', work_path, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "waves-effect waves-teal btn red"
      - else
        = link_to 'Regresar', works_path, :class => "waves-effect waves-teal btn indigo"